VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "trusty"
  config.vm.define :elasticsearch do |t|
  end

  config.vm.provider "vmware_fusion" do |v|
    v.name = "elasticsearch"
    v.vmx["name"] = "elasticsearch"   
    v.memory = 2048;
  end

  config.vm.provision "shell", inline: "wget -qO - http://packages.elasticsearch.org/GPG-KEY-elasticsearch | apt-key add -"
  config.vm.provision "shell", inline: "echo 'deb http://packages.elasticsearch.org/elasticsearch/1.4/debian stable main' >> /etc/apt/sources.list"
  config.vm.provision "shell", inline: "add-apt-repository -y ppa:webupd8team/java"
  config.vm.provision "shell", inline: "apt-get update"
  config.vm.provision "shell", inline: "apt-get install -y openjdk-7-jre-headless"
  config.vm.provision "shell", inline: "apt-get install -y elasticsearch"
  config.vm.provision "shell", inline: "/usr/share/elasticsearch/bin/plugin -install royrusso/elasticsearch-HQ"
  config.vm.provision "shell", inline: "update-rc.d elasticsearch defaults 95 10"
  config.vm.provision "shell", inline: "service elasticsearch restart"
  config.vm.provision "shell", inline: "apt-get -y dist-upgrade"

  config.vm.network "forwarded_port", guest: 9200, host: 9200
end
