VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "trusty"

  config.vm.provider "vmware_fusion" do |v|
    v.vmx["name"] = "postgres"
    v.vmx["memsize"] = "512"
  end

  config.vm.provision "shell", inline: "apt-get update"
  config.vm.provision "shell", inline: "apt-get install -y postgresql htop"
  config.vm.provision "shell", inline: "apt-get -y dist-upgrade"
  config.vm.network "forwarded_port", guest: 5432, host: 5432
end
