VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "trusty"
  config.vm.define :mysql do |t|
  end

  config.vm.provider "vmware_fusion" do |v|
    v.name = "mysql"
    v.vmx["name"] = "mysql"
    v.vmx["memsize"] = "512"
  end

  config.vm.provision "shell", inline: "apt-get update"
  config.vm.provision "shell", inline: "apt-get install -y mysql-server"
  config.vm.provision "shell", inline: "apt-get -y dist-upgrade"
  config.vm.network "forwarded_port", guest: 3306, host: 3306
end
